CREATE TABLE IF NOT EXISTS hw1.okved (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	code VARCHAR,
	parent_code VARCHAR,
	section VARCHAR,
	name VARCHAR,
	comment VARCHAR,
	load_dttm TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(code)
	);